#docker-compose.yml

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - net
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
    networks:
      - net
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - net

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/dimarque/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/dimarque/data/mariadb
      o: bind

networks:
  net:
    driver: bridge